name: first 

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

env:
    class: "Day 2 bootcamp"
    env_scope: "global"

jobs:
    runcommands-job1:
        runs-on: ubuntu-latest
        env:
            job: "runcommands"
            

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Run the single  commands
              run: |
               echo "hello world"
               echo " scope: ${{ env.env_scope }}"
               echo " job: ${{ env.job }}"
               echo " step: ${{ env.step }}"
            
            - name: Run the multiple commands
              env:
                step: "checkout"
                env_scope: "step"
              run: |
                echo "this is multiple line commands"
                echo " scope: ${{ env.env_scope }}"
                echo " job: ${{ env.job }}"
                echo " step: ${{ env.step }}"


    runcommands-job2:
        runs-on: ubuntu-latest
        needs: [ runcommands-job1]

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Run the single  commands
              run: echo "hello world"
            
            - name: Run the multiple commands
              run: |
                echo "this is multiple line commands"
                echo "this is very useful"
    
    runcommands-job3:
        runs-on: ubuntu-latest
        needs: [ runcommands-job1,  runcommands-job2]

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Run the single  commands
              run: echo "hello world"
            
            - name: Run the multiple commands
              run: |
                echo "this is multiple line commands"
                echo "this is very useful"
